# this is a copy of the dependencies listed in the gemspec,
# since bundix doesn't support reading the gemspec itself.
source 'https://rubygems.org'

gem 'actionpack', '~> 5.2'

group :development do
  gem 'rails', '~> 5.2'
  gem 'sqlite3', '~> 1.4.0'
  gem 'rake', '~> 12.3'
  gem 'rspec', '~> 3.8'
end
