# this is a copy of the dependencies listed in the gemspec,
# since bundix doesn't support reading the gemspec itself.
source 'https://rubygems.org'

gem 'actionpack', '~> 6.0'

group :development do
  gem 'rails', '~> 6.0'
  gem 'sqlite3', '~> 1.4.0'
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.9'
end
