language: ruby
rvm:
  - 2.3.4
  - 2.4.3
  - 2.5.0
  - 2.6.6
  - 2.7.2
before_install:
  - gem update --system
  - gem install bundler
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
