sudo: false
language: ruby
rvm:
  - 2.3.4
  - 2.4.3
  - 2.5.0
# from https://docs.travis-ci.com/user/languages/ruby/#bundler-20
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
