# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f8411183a7ecfd81f871f149c9111bfb3673934e6ecf12ac8302a83f19eae41476e681429013f1486db4b2f29ac46f1cd7c14714a089f58b2eec6c23b880c6f

test:
  secret_key_base: 921bd0e70239917abaea7c2c2d195e80ea800034cab610a03cdcd9040e7879c33a4e3bf95bfbeaf473d45fccace1edc293534fa713b7e1dc8168ea39e303cc6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
