#!/usr/bin/env ruby
# frozen_string_literal: true

require 'open3'
require 'rails_edge_test'

# Walk up recursively the filesystem until we can find a folder
# containing the Gemfile. Then we can use that folder as the starting
# point to look for the rails files that we need.
def find_gemfile_dir(path)
  if File.file?(File.join(path, 'Gemfile'))
    path
  else
    new_path = File.expand_path('..', path)

    raise 'Could not find directory with Gemfile' if path == new_path

    find_gemfile_dir(new_path)

  end
end

gemfile_dir = find_gemfile_dir(Dir.pwd)
RailsEdgeTest::Runner.load_rails_environment!(gemfile_dir)
RailsEdgeTest::Runner.go!(ARGV)
