name: Run tests
on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

  # We also provide a way to run this manually, if needed.
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: nix-shell --run rspec
